"""Discover host graphics inputs; CDI remains generated by NVIDIA's toolkit."""
import json
import os
from pathlib import Path
import re
import subprocess

import yaml

from .common import Failure, digest, run, write_json


def node_identity(path):
    device = Path('/sys/class/drm') / Path(path).name / 'device'
    try:
        vendor = (device / 'vendor').read_text().strip()
    except OSError:
        vendor = None
    driver = (device / 'driver').resolve().name if (device / 'driver').exists() else None
    return {'vendor': vendor, 'driver': driver}


def provider(config, node):
    hardware = node_identity(node)
    selected = config.get('graphicsProvider', 'auto')
    if selected not in {'auto', 'mesa', 'nvidia-cdi'}:
        raise Failure('graphicsProvider must be auto, mesa or nvidia-cdi', 2)
    if selected == 'auto':
        selected = 'nvidia-cdi' if hardware['driver'] == 'nvidia' else 'mesa'
    if selected == 'mesa':
        if hardware['driver'] == 'nvidia':
            raise Failure('the proprietary NVIDIA node requires graphicsProvider nvidia-cdi', 3)
    elif hardware['driver'] != 'nvidia':
        raise Failure('nvidia-cdi requires a render node bound to the NVIDIA driver', 2)
    return {'provider': selected, 'renderNode': node, **hardware}


def plan(config, node, rt, hashes=True):
    result = provider(config, node)
    if result['provider'] == 'mesa':
        return result
    requested = config.get('cdiDevice')
    if requested and not re.fullmatch(r'nvidia\.com/gpu=[A-Za-z0-9_.-]+', requested):
        raise Failure('cdiDevice must be a qualified NVIDIA CDI device', 2)
    directories = rt['info'].get('CDISpecDirs', [])
    matches = []
    for directory in directories:
        for path in sorted(Path(directory).glob('*')):
            if path.suffix not in {'.json', '.yaml', '.yml'} or not path.is_file():
                continue
            if path.stat().st_size > 2 * 1024 * 1024:
                raise Failure('CDI spec exceeds the bounded parser size', 2, path=str(path))
            try:
                spec = yaml.safe_load(path.read_text())
            except yaml.YAMLError as exc:
                raise Failure('invalid generated CDI YAML/JSON', 3, path=str(path), error=str(exc)) from exc
            if not isinstance(spec, dict) or spec.get('kind') != 'nvidia.com/gpu':
                continue
            validate_spec(spec, path)
            for device in spec.get('devices', []):
                name = 'nvidia.com/gpu=' + device['name']
                edits = device.get('containerEdits', {})
                nodes = [entry.get('hostPath') or entry.get('path') for entry in edits.get('deviceNodes', [])]
                if node in nodes and (name == requested if requested else device['name'].startswith('GPU-')):
                    matches.append((path, spec, device, name))
    if len(matches) != 1:
        raise Failure('select one generated CDI device matching the render node; remove stale/duplicate specs or regenerate with nvidia-ctk cdi generate',
                      3, candidates=[{'spec': str(path), 'device': name} for path, _, _, name in matches])
    path, spec, device, name = matches[0]
    edits = [spec.get('containerEdits', {}), device.get('containerEdits', {})]
    mounts = [mount for edit in edits for mount in edit.get('mounts', [])]
    missing = [mount['hostPath'] for mount in mounts if not Path(mount['hostPath']).exists()]
    hooks = [hook['path'] for edit in edits for hook in edit.get('hooks', [])]
    missing += [hook for hook in hooks if not Path(hook).is_file()]
    if missing:
        raise Failure('NVIDIA CDI is stale: regenerate it with nvidia-ctk cdi generate before launching the devbox', 3,
                      spec=str(path), missing=missing,
                      refreshCommand=['nvidia-ctk', 'cdi', 'generate', '--output=' + str(path)])
    inputs = []
    libraries, vendor_files, vulkan_files, gbm_dirs = set(), [], [], set()
    for mount in mounts:
        target, source = mount['containerPath'], Path(mount['hostPath'])
        if any(part in {'', '..'} for part in Path(target).parts[1:]) or not target.startswith('/'):
            raise Failure('unsafe CDI container mount target', 2)
        if source.is_file():
            item = {'hostPath': str(source), 'containerPath': target, 'size': source.stat().st_size}
            if hashes:
                item['sha256'] = digest(source)
            inputs.append(item)
        if Path(target).name.startswith('lib') and 'nvidia' in Path(target).name:
            libraries.add(str(Path(target).parent))
        if '/glvnd/egl_vendor.d/' in target:
            vendor_files.append(target)
        if '/vulkan/icd.d/' in target:
            vulkan_files.append(target)
    for edit in edits:
        for hook in edit.get('hooks', []):
            for argument in hook.get('args', []):
                if '::' in argument and '/gbm/' in argument:
                    gbm_dirs.add(str(Path(argument.split('::', 1)[1]).parent))
    if not libraries or not vendor_files or not gbm_dirs:
        raise Failure('generated CDI spec lacks EGL libraries, vendor registration or GBM backend', 3)
    result.update(cdiDevice=name, spec={'path': str(path), 'sha256': digest(path)},
                  inputs=inputs, hooks=[{'path': hook, 'sha256': digest(hook)} for hook in sorted(set(hooks))],
                  libraryDirectories=sorted(libraries), eglVendorFiles=sorted(vendor_files),
                  vulkanIcdFiles=sorted(vulkan_files), gbmBackendDirectories=sorted(gbm_dirs))
    return result


def validate_spec(spec, path):
    def require(condition):
        if not condition:
            raise ValueError('invalid CDI field')

    try:
        devices = spec.get('devices', [])
        require(isinstance(devices, list))
        edits = [spec.get('containerEdits', {})]
        for device in devices:
            require(isinstance(device, dict) and isinstance(device['name'], str))
            edits.append(device.get('containerEdits', {}))
        for edit in edits:
            require(isinstance(edit, dict))
            for key in ['mounts', 'deviceNodes', 'hooks']:
                require(isinstance(edit.get(key, []), list))
                for entry in edit.get(key, []):
                    require(isinstance(entry, dict))
                    for field in (['hostPath', 'containerPath'] if key == 'mounts' else ['path']):
                        require(isinstance(entry[field], str) and entry[field].startswith('/') and '\0' not in entry[field])
                    if key == 'deviceNodes' and 'hostPath' in entry:
                        require(isinstance(entry['hostPath'], str) and entry['hostPath'].startswith('/'))
                    if key == 'hooks':
                        require(isinstance(entry.get('args', []), list) and all(isinstance(v, str) for v in entry.get('args', [])))
    except (ValueError, KeyError, TypeError) as exc:
        raise Failure('invalid generated CDI structure', 3, path=str(path)) from exc


def private_runtime_preferred(config):
    node = config.get('renderNode', 'auto')
    if node == 'auto':
        nodes = [str(path) for path in Path('/dev/dri').glob('renderD*') if os.access(path, os.R_OK | os.W_OK)]
        node = nodes[0] if len(nodes) == 1 else None
    return bool(node and provider(config, node)['provider'] == 'nvidia-cdi')


def readiness(config, node, rt):
    result = provider(config, node)
    if result['provider'] == 'mesa':
        return result
    if not os.environ.get('WB_NVIDIA_CTK') or not os.environ.get('WB_NVIDIA_CDI_HOOK'):
        raise Failure('NVIDIA CDI requires the Linux Nix toolkit backend', 3)
    if rt['kind'] != 'podman':
        raise Failure('NVIDIA devboxes use Nix-pinned rootless Podman with private CDI; create with --runtime podman', 3)
    result.update(injection='private-cdi')
    return result


def launch_plan(ws, config, node, rt, operation_id):
    ready = readiness(config, node, rt)
    if ready['provider'] == 'mesa':
        return ready
    generated = prepare(ws, operation_id, node, config.get('cdiDevice'))
    result = {**generated['graphics'], **ready, 'generationManifest': generated['manifest']}
    result['runtimeArguments'] = ['--cdi-spec-dir', str(Path(result['spec']['path']).parent),
                                  '--hooks-dir', os.environ['WB_CONTAINER_HOOKS_DIR']]
    result['runArguments'] = ['--device', result['cdiDevice']]
    return result


def prepare(ws, operation_id, render_node=None, cdi_device=None):
    tool, hook = os.environ.get('WB_NVIDIA_CTK'), os.environ.get('WB_NVIDIA_CDI_HOOK')
    if not tool or not hook:
        raise Failure('NVIDIA CDI generation requires the Linux Nix toolkit backend', 3)
    nodes = [str(path) for path in Path('/dev/dri').glob('renderD*')
             if node_identity(path)['driver'] == 'nvidia' and os.access(path, os.R_OK | os.W_OK)]
    node = render_node or (nodes[0] if len(nodes) == 1 else None)
    if node not in nodes:
        raise Failure('select one accessible NVIDIA render node for CDI generation', 3, renderNodes=nodes)
    directory = ws.state / 'gpu' / operation_id
    directory.mkdir(parents=True, mode=0o700)
    path = directory / 'nvidia.yaml'
    command = [tool, 'cdi', 'generate', '--nvidia-cdi-hook-path', hook, '--output=' + str(path)]
    try:
        result = subprocess.run(command, capture_output=True, text=True, timeout=60)
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise Failure('NVIDIA CDI generator could not complete', 3, command=command, error=str(exc)) from exc
    (directory / 'generator.log').write_text(result.stderr)
    if result.returncode:
        raise Failure('NVIDIA CDI generator failed', result.returncode, log=str(directory / 'generator.log'))
    observed = plan({'cdiDevice': cdi_device}, node, {'info': {'CDISpecDirs': [str(directory)]}})
    version = run([tool, '--version']).stdout.strip()
    root = os.environ['WB_NVIDIA_TOOLKIT_ROOT']
    run([os.environ['WB_NIX'], 'build', '--out-link', directory / 'toolkit', root])
    hook_root = str(Path(hook).parent.parent)
    run([os.environ['WB_NIX'], 'build', '--out-link', directory / 'hooks', hook_root])
    receipt = {'schemaVersion': 1, 'operationId': operation_id, 'state': 'prepared',
               'manifest': str(directory / 'manifest.json'),
               'nixLockSha256': digest(ws.root / 'devenv.lock'),
               'generator': {'command': command, 'version': version, 'sha256': digest(tool), 'storeRoot': root, 'hookStoreRoot': hook_root},
               'graphics': observed,
               'runtime': {'kind': 'podman', 'arguments': ['--cdi-spec-dir', str(directory)]},
               'integration': 'The launcher passes this private CDI directory directly; no system CDI setup is needed.'}
    write_json(directory / 'manifest.json', receipt)
    ws.journal(operation_id, {'kind': 'devbox-cdi-prepare', 'state': 'prepared', 'manifest': str(directory / 'manifest.json')})
    return receipt
